name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = { path = "../.." }
gleam_crypto = "~> 1.0"
gleam_erlang = "~> 0.23"
mist = ">= 1.2.0 and < 2.0.0"
gleam_http = "~> 3.5"

[dev-dependencies]
gleeunit = "~> 1.0"
