name = "wisp_mist"
version = "1.0.0"
gleam = ">= 1.11.0"
description = "A Mist adapter for Wisp"
licences = ["Apache-2.0"]

repository = { type = "github", user = "gleam-wisp", repo = "wisp" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/lpil" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
exception = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
