name = "app"
version = "1.0.0"
description = "A Wisp example"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = { path = "../.." }
gleam_json = "~> 0.6"
tiny_database = { path = "../utilities/tiny_database" }

[dev-dependencies]
gleeunit = "~> 0.10"
