name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.30.0 and < 2.0.0"
wisp = { path = "../.." }
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 0.23.0 and < 2.0.0"
mist = ">= 4.0.0 and < 5.0.0"
gleam_http = ">= 3.5.0 and < 4.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
